# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.srcs/sources_1/ip/pll_pixelclock_1/pll_pixelclock.xci
# IP: The module: 'pll_pixelclock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.gen/sources_1/ip/pll_pixelclock_1/pll_pixelclock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_pixelclock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.gen/sources_1/ip/pll_pixelclock_1/pll_pixelclock.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.gen/sources_1/ip/pll_pixelclock_1/pll_pixelclock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.srcs/sources_1/ip/pll_pixelclock_1/pll_pixelclock.xci
# IP: The module: 'pll_pixelclock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.gen/sources_1/ip/pll_pixelclock_1/pll_pixelclock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.gen/sources_1/ip/pll_pixelclock_1/pll_pixelclock.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/aokim/Company/RISCV/RockWave/SYNTH/Zedboard/Zedboard.gen/sources_1/ip/pll_pixelclock_1/pll_pixelclock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
